#pragma checksum "D:\Github\SakerProgrammering\Admin.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AEBCB9011744D5B81C84DC1ECB26A5292C61E719"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 16 "D:\Github\SakerProgrammering\Admin.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    
    #line default
    #line hidden
    
    
    #line 17 "D:\Github\SakerProgrammering\Admin.aspx"
    protected global::System.Web.UI.WebControls.Button btnSearch;
    
    #line default
    #line hidden
    
    
    #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
    protected global::System.Web.UI.WebControls.RangeValidator RangeValidator1;
    
    #line default
    #line hidden
    
    
    #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_aspx : global::Admin, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Github\SakerProgrammering\Admin.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Admin.aspx";
                dependencies[1] = "~/Admin.aspx.cs";
                global::ASP.admin_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        90,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.2.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        185,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        158,
                        51,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        209,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <div>\r\n            <h1>Admin</h1>\r\n\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        255,
                        59,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control7() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.Text = "Ange anställningsnummer:";
            
            #line default
            #line hidden
            
            #line 14 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.AssociatedControlID = "txtSearch";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        314,
                        92,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div>\r\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        406,
                        37,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSearch() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 16 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtSearch = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 16 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ID = "txtSearch";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        443,
                        57,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        500,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSearch() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 17 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnSearch = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 17 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ID = "btnSearch";
            
            #line default
            #line hidden
            
            #line 17 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.Text = "Sök";
            
            #line default
            #line hidden
            
            #line 17 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnSearch_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        518,
                        81,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        599,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RangeValidator @__BuildControlRangeValidator1() {
            global::System.Web.UI.WebControls.RangeValidator @__ctrl;
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RangeValidator();
            
            #line default
            #line hidden
            this.RangeValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ID = "RangeValidator1";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ErrorMessage = "Ange ett anställningsnummer från 1 - 999999999";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.MaximumValue = "999999999";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.MinimumValue = "1";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ControlToValidate = "txtSearch";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.EnableClientScript = false;
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 51, 0)));
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        617,
                        291,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            </div>\r\n        </div>\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        908,
                        44,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl2 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl4 = this.@__BuildControltxtSearch();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl6;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl6 = this.@__BuildControlbtnSearch();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl7 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RangeValidator @__ctrl8;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl8 = this.@__BuildControlRangeValidator1();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        223,
                        736,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        959,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_aspx @__ctrl) {
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__ctrl5 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\Github\SakerProgrammering\Admin.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1345565500;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
