#pragma checksum "D:\Github\SakerProgrammering\Default.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B7D3C7AD5611DFC24D87BD8DDE2F7A6964571D87"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtUsUserId;
    
    #line default
    #line hidden
    
    
    #line 13 "D:\Github\SakerProgrammering\Default.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revNumber;
    
    #line default
    #line hidden
    
    
    #line 16 "D:\Github\SakerProgrammering\Default.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtpassword;
    
    #line default
    #line hidden
    
    
    #line 18 "D:\Github\SakerProgrammering\Default.aspx"
    protected global::System.Web.UI.WebControls.Button btnLogin;
    
    #line default
    #line hidden
    
    
    #line 10 "D:\Github\SakerProgrammering\Default.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 12 "D:\Github\SakerProgrammering\Default.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class default_aspx : global::_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public default_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Github\SakerProgrammering\Default.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Default.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.default_aspx.@__initialized == false)) {
                global::ASP.default_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/Default.aspx";
                dependencies[1] = "~/Default.aspx.cs";
                global::ASP.default_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.default_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtUsUserId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 12 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtUsUserId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 12 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ID = "txtUsUserId";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlrevNumber() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 13 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.revNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 13 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ID = "revNumber";
            
            #line default
            #line hidden
            
            #line 13 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ControlToValidate = "txtUsUserId";
            
            #line default
            #line hidden
            
            #line 13 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ErrorMessage = "Not a number";
            
            #line default
            #line hidden
            
            #line 13 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ValidationExpression = "[0-9]";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtpassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 16 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtpassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 16 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ID = "txtpassword";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnLogin() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 18 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnLogin = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ID = "btnLogin";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.Text = "Login";
            
            #line default
            #line hidden
            
            #line 18 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnLogin_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        UserId\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl1 = this.@__BuildControltxtUsUserId();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl2;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl2 = this.@__BuildControlrevNumber();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <br />\r\n        Password\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl3 = this.@__BuildControltxtpassword();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <br />\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl4 = this.@__BuildControlbtnLogin();
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 10 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(default_aspx @__ctrl) {
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\Github\SakerProgrammering\Default.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.default_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.default_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 963369283;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
