#pragma checksum "D:\Github\SakerProgrammering\Employee.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5BC6FD52BB151B05785F9B1793DD52AE68B48924"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Employee : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.Label lblFromDate;
    
    #line default
    #line hidden
    
    
    #line 67 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtFromDate;
    
    #line default
    #line hidden
    
    
    #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator txtFromDateValidator;
    
    #line default
    #line hidden
    
    
    #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
    
    #line default
    #line hidden
    
    
    #line 81 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.Label lblToDate;
    
    #line default
    #line hidden
    
    
    #line 82 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtToDate;
    
    #line default
    #line hidden
    
    
    #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator txtToDateValidator;
    
    #line default
    #line hidden
    
    
    #line 86 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 87 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtChild;
    
    #line default
    #line hidden
    
    
    #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator txtChildValidator;
    
    #line default
    #line hidden
    
    
    #line 90 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.WebControls.Button btnSubmit;
    
    #line default
    #line hidden
    
    
    #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class employee_aspx : global::Employee, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public employee_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\Github\SakerProgrammering\Employee.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Employee.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.employee_aspx.@__initialized == false)) {
                global::ASP.employee_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/Employee.aspx";
                dependencies[1] = "~/Employee.aspx.cs";
                global::ASP.employee_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.employee_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 8 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 8 "D:\Github\SakerProgrammering\Employee.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 8 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Href = "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css";
            
            #line default
            #line hidden
            
            #line 8 "D:\Github\SakerProgrammering\Employee.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "html/css");
            
            #line default
            #line hidden
            
            #line 8 "D:\Github\SakerProgrammering\Employee.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("media", "all");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 6 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 6 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control2));
            return @__ctrl;
        }
        
        private void @__Render__control2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            parameterContainer.Controls[1].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 0, 419, true);
            
            #line 17 "D:\Github\SakerProgrammering\Employee.aspx"
                               @__w.Write( DateTime.Now.ToString("yyyy-MM-dd") );

            
            #line default
            #line hidden
            @__w.Write("\');\r\n                $(\'#txtFromDate\').datepicker({\r\n                    dateForm" +
                    "at: \'yy-mm-dd\'\r\n                });\r\n\r\n                $(\'#txtToDate\').val(\'");
            
            #line 22 "D:\Github\SakerProgrammering\Employee.aspx"
                             @__w.Write( DateTime.Now.ToString("yyyy-MM-dd") );

            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 419, 1400, false);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblFromDate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblFromDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "lblFromDate";
            
            #line default
            #line hidden
            
            #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Från och med:";
            
            #line default
            #line hidden
            
            #line 66 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.AssociatedControlID = "txtFromDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtFromDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 67 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtFromDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 67 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtFromDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControltxtFromDateValidator() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.txtFromDateValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtFromDateValidator";
            
            #line default
            #line hidden
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ErrorMessage = "Ange ett datum med formatet: ÅÅÅÅ-MM-DD";
            
            #line default
            #line hidden
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ValidationExpression = "^(19|20)\\d\\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$";
            
            #line default
            #line hidden
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ControlToValidate = "txtFromDate";
            
            #line default
            #line hidden
            
            #line 68 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 51, 0)));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 74 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 74 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Selected = true;
            
            #line default
            #line hidden
            
            #line 74 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Första sjukdagen";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 75 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 75 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Sjukskriven av läkare";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 76 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 76 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Vård av barn";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl2 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RadioButtonList @__BuildControlRadioButtonList1() {
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl;
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RadioButtonList();
            
            #line default
            #line hidden
            this.RadioButtonList1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "RadioButtonList1";
            
            #line default
            #line hidden
            
            #line 73 "D:\Github\SakerProgrammering\Employee.aspx"
            this.@__BuildControl__control5(@__ctrl.Items);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblToDate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 81 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblToDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 81 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "lblToDate";
            
            #line default
            #line hidden
            
            #line 81 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Till och med:";
            
            #line default
            #line hidden
            
            #line 81 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.AssociatedControlID = "txtToDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtToDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 82 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtToDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 82 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtToDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControltxtToDateValidator() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.txtToDateValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtToDateValidator";
            
            #line default
            #line hidden
            
            #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ErrorMessage = "Ange ett datum med formatet: ÅÅÅÅ-MM-DD";
            
            #line default
            #line hidden
            
            #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ValidationExpression = "^(19|20)\\d\\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$";
            
            #line default
            #line hidden
            
            #line 83 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ControlToValidate = "txtToDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 86 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 86 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            
            #line 86 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Barnets Personnummer:";
            
            #line default
            #line hidden
            
            #line 86 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.AssociatedControlID = "txtChild";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtChild() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 87 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtChild = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 87 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtChild";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControltxtChildValidator() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.txtChildValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "txtChildValidator";
            
            #line default
            #line hidden
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ErrorMessage = "Ange ett personnummer med formatet: \"ÅÅMMDD-xxxx\"";
            
            #line default
            #line hidden
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ValidationExpression = "\\d{6}-\\d{4}";
            
            #line default
            #line hidden
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ControlToValidate = "txtChild";
            
            #line default
            #line hidden
            
            #line 88 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 51, 0)));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 90 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 90 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "btnSubmit";
            
            #line default
            #line hidden
            
            #line 90 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Text = "Skicka";
            
            #line default
            #line hidden
            
            #line 90 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnSubmit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div>\r\n        <h1>Sjukanmälan</h1>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl1 = this.@__BuildControllblFromDate();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl2 = this.@__BuildControltxtFromDate();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl3;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl3 = this.@__BuildControltxtFromDateValidator();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <br />\r\n        <div id=\"radioDiv\">\r\n        <fieldset>\r\n        <legen" +
                        "d>Välj ett alternativ</legend>\r\n            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RadioButtonList @__ctrl4;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl4 = this.@__BuildControlRadioButtonList1();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </fieldset>\r\n        </div>\r\n        <div id=\"DivDoctor\" style=\"display" +
                        ": none\">\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl5;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl5 = this.@__BuildControllblToDate();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl6 = this.@__BuildControltxtToDate();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl7;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl7 = this.@__BuildControltxtToDateValidator();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n            <div id=\"DivChild\" style=\"display: none\">\r\n    " +
                        "            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl8;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl8 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl9 = this.@__BuildControltxtChild();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl10;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl10 = this.@__BuildControltxtChildValidator();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl11;
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl11 = this.@__BuildControlbtnSubmit();
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 63 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(employee_aspx @__ctrl) {
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "D:\Github\SakerProgrammering\Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\Github\SakerProgrammering\Employee.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.employee_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.employee_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -584649338;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
